function net = CNN_SqueezeNet(numFeatures,sequenceLength)
%% Create Deep Learning Network Architecture (1D Version)
% Script for creating the layers for a deep learning network with the following
% properties (converted to 1D):
%
%  Number of layers: 68
%  Number of connections: 75
%
% Auto-generated by MATLAB on 09-Jan-2025 (converted to 1D sequences).



net = layerGraph();

%% Add Layer Branches
% Add branches to the dlnetwork. Each branch is a linear array of layers.

% --- First branch (original "data" -> "conv1" -> "relu_conv1" -> "pool1" -> "fire2-squeeze1x1" -> "fire2-relu_squeeze1x1")
tempNet = [
    sequenceInputLayer(numFeatures,'Name','data','MinLength',sequenceLength)  % 1D input of length 227
    convolution1dLayer(3,64,'Name','conv1','Stride',2,'Padding','same')
    reluLayer('Name','relu_conv1')
    maxPooling1dLayer(3,'Name','pool1','Stride',2,'Padding','same')

    convolution1dLayer(1,16,'Name','fire2-squeeze1x1','Padding','same')
    reluLayer('Name','fire2-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire2 expand1x1
tempNet = [
    convolution1dLayer(1,64,'Name','fire2-expand1x1','Padding','same')
    reluLayer('Name','fire2-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire2 expand3x3
tempNet = [
    convolution1dLayer(3,64,'Name','fire2-expand3x3','Padding','same')
    reluLayer('Name','fire2-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire2 concat -> next squeeze
tempNet = [
    depthConcatenationLayer(2,'Name','fire2-concat')
    convolution1dLayer(1,16,'Name','fire3-squeeze1x1','Padding','same')
    reluLayer('Name','fire3-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire3 expand1x1
tempNet = [
    convolution1dLayer(1,64,'Name','fire3-expand1x1','Padding','same')
    reluLayer('Name','fire3-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire3 expand3x3
tempNet = [
    convolution1dLayer(3,64,'Name','fire3-expand3x3','Padding','same')
    reluLayer('Name','fire3-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire3 concat -> pool3 -> fire4-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire3-concat')
    maxPooling1dLayer(3,'Name','pool3','Stride',2,'Padding','same')
    convolution1dLayer(1,32,'Name','fire4-squeeze1x1','Padding','same')
    reluLayer('Name','fire4-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire4 expand1x1
tempNet = [
    convolution1dLayer(1,128,'Name','fire4-expand1x1','Padding','same')
    reluLayer('Name','fire4-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire4 expand3x3
tempNet = [
    convolution1dLayer(3,128,'Name','fire4-expand3x3','Padding','same')
    reluLayer('Name','fire4-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire4 concat -> fire5-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire4-concat')
    convolution1dLayer(1,32,'Name','fire5-squeeze1x1','Padding','same')
    reluLayer('Name','fire5-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire5 expand1x1
tempNet = [
    convolution1dLayer(1,128,'Name','fire5-expand1x1','Padding','same')
    reluLayer('Name','fire5-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire5 expand3x3
tempNet = [
    convolution1dLayer(3,128,'Name','fire5-expand3x3','Padding','same')
    reluLayer('Name','fire5-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire5 concat -> pool5 -> fire6-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire5-concat')
    maxPooling1dLayer(3,'Name','pool5','Stride',2,'Padding','same')
    convolution1dLayer(1,48,'Name','fire6-squeeze1x1','Padding','same')
    reluLayer('Name','fire6-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire6 expand1x1
tempNet = [
    convolution1dLayer(1,192,'Name','fire6-expand1x1','Padding','same')
    reluLayer('Name','fire6-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire6 expand3x3
tempNet = [
    convolution1dLayer(3,192,'Name','fire6-expand3x3','Padding','same')
    reluLayer('Name','fire6-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire6 concat -> fire7-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire6-concat')
    convolution1dLayer(1,48,'Name','fire7-squeeze1x1','Padding','same')
    reluLayer('Name','fire7-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire7 expand1x1
tempNet = [
    convolution1dLayer(1,192,'Name','fire7-expand1x1','Padding','same')
    reluLayer('Name','fire7-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire7 expand3x3
tempNet = [
    convolution1dLayer(3,192,'Name','fire7-expand3x3','Padding','same')
    reluLayer('Name','fire7-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire7 concat -> fire8-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire7-concat')
    convolution1dLayer(1,64,'Name','fire8-squeeze1x1','Padding','same')
    reluLayer('Name','fire8-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire8 expand1x1
tempNet = [
    convolution1dLayer(1,256,'Name','fire8-expand1x1','Padding','same')
    reluLayer('Name','fire8-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire8 expand3x3
tempNet = [
    convolution1dLayer(3,256,'Name','fire8-expand3x3','Padding','same')
    reluLayer('Name','fire8-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire8 concat -> fire9-squeeze1x1
tempNet = [
    depthConcatenationLayer(2,'Name','fire8-concat')
    convolution1dLayer(1,64,'Name','fire9-squeeze1x1','Padding','same')
    reluLayer('Name','fire9-relu_squeeze1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire9 expand1x1
tempNet = [
    convolution1dLayer(1,256,'Name','fire9-expand1x1','Padding','same')
    reluLayer('Name','fire9-relu_expand1x1')
    ];
net = addLayers(net,tempNet);

% --- Fire9 expand3x3
tempNet = [
    convolution1dLayer(3,256,'Name','fire9-expand3x3','Padding','same')
    reluLayer('Name','fire9-relu_expand3x3')
    ];
net = addLayers(net,tempNet);

% --- Fire9 concat -> drop9 -> conv10 -> relu_conv10 -> pool10 -> softmax -> flatten
tempNet = [
    depthConcatenationLayer(2,'Name','fire9-concat')
    dropoutLayer(0.5,'Name','drop9')
    convolution1dLayer(1,1000,'Name','conv10','Padding','same')
    reluLayer('Name','relu_conv10')
    globalAveragePooling1dLayer('Name','pool10')
    %softmaxLayer('Name','prob')
    %flattenLayer('Name','prob_flatten')
    fullyConnectedLayer(1,'Name','fc_final')
    ];
net = addLayers(net,tempNet);



%% Connect Layer Branches
% Connect all the branches of the network to create the network graph.

net = connectLayers(net,'fire2-relu_squeeze1x1','fire2-expand1x1');
net = connectLayers(net,'fire2-relu_squeeze1x1','fire2-expand3x3');
net = connectLayers(net,'fire2-relu_expand1x1','fire2-concat/in1');
net = connectLayers(net,'fire2-relu_expand3x3','fire2-concat/in2');

net = connectLayers(net,'fire3-relu_squeeze1x1','fire3-expand1x1');
net = connectLayers(net,'fire3-relu_squeeze1x1','fire3-expand3x3');
net = connectLayers(net,'fire3-relu_expand1x1','fire3-concat/in1');
net = connectLayers(net,'fire3-relu_expand3x3','fire3-concat/in2');

net = connectLayers(net,'fire4-relu_squeeze1x1','fire4-expand1x1');
net = connectLayers(net,'fire4-relu_squeeze1x1','fire4-expand3x3');
net = connectLayers(net,'fire4-relu_expand1x1','fire4-concat/in1');
net = connectLayers(net,'fire4-relu_expand3x3','fire4-concat/in2');

net = connectLayers(net,'fire5-relu_squeeze1x1','fire5-expand1x1');
net = connectLayers(net,'fire5-relu_squeeze1x1','fire5-expand3x3');
net = connectLayers(net,'fire5-relu_expand1x1','fire5-concat/in1');
net = connectLayers(net,'fire5-relu_expand3x3','fire5-concat/in2');

net = connectLayers(net,'fire6-relu_squeeze1x1','fire6-expand1x1');
net = connectLayers(net,'fire6-relu_squeeze1x1','fire6-expand3x3');
net = connectLayers(net,'fire6-relu_expand1x1','fire6-concat/in1');
net = connectLayers(net,'fire6-relu_expand3x3','fire6-concat/in2');

net = connectLayers(net,'fire7-relu_squeeze1x1','fire7-expand1x1');
net = connectLayers(net,'fire7-relu_squeeze1x1','fire7-expand3x3');
net = connectLayers(net,'fire7-relu_expand1x1','fire7-concat/in1');
net = connectLayers(net,'fire7-relu_expand3x3','fire7-concat/in2');

net = connectLayers(net,'fire8-relu_squeeze1x1','fire8-expand1x1');
net = connectLayers(net,'fire8-relu_squeeze1x1','fire8-expand3x3');
net = connectLayers(net,'fire8-relu_expand1x1','fire8-concat/in1');
net = connectLayers(net,'fire8-relu_expand3x3','fire8-concat/in2');

net = connectLayers(net,'fire9-relu_squeeze1x1','fire9-expand1x1');
net = connectLayers(net,'fire9-relu_squeeze1x1','fire9-expand3x3');
net = connectLayers(net,'fire9-relu_expand1x1','fire9-concat/in1');
net = connectLayers(net,'fire9-relu_expand3x3','fire9-concat/in2');

end

